#!/usr/bin/env bash
# Script displays "To infinity and beyond"
# Displays "I am Invincable
# The 67-stop_me_now
count=1

	trap "echo 'I am invincible!!!'" SIGTERM
while [ $count ]
do
	#trap "echo I am invincible!!!" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
