#!/usr/bin/env bash
#Information about the school
f=school
if [ -e "$f" ]
then
	echo "school file exists"
else
	echo "school file does not exist"
fi
if [ ! -s "$f" ]
then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [ -f "$f" ]
then
	echo "school is regular file"
fi
